#include<iostream>
#include<string.h>
#include<fstream>
#include<iomanip>
#include <cmath>
#include <algorithm>
#include <cctype>
#include <string>
using namespace std;
void swaap(long long x , long long y)
{   
  cout<<y<<" "<<x;

};
int main()
{
 long long sum=0,x,y,z,j,i,d,f,mx=0,mn=0,row,colm;
 bool found=true;
 bool tt=true;
 long long freq[256] = {0};
 long long a[100000];
 string s,h;
 char c;
 
 cin>>x>>y;
 swaap(x,y);



}           

